micronaut:
  application:
    name: account
  security:
    reject-not-found: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
cassandra:
  default:
    basic:
      contact-points:
        - ${CASSANDRA_POINT}
      load-balancing-policy:
        local-datacenter: datacenter1

