micronaut:
  application:
    name: account
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT20.00S
        descriptions: true
  security:
    reject-not-found: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
endpoints:
  prometheus:
    sensitive: false
  metrics:
    sensitive: false

cassandra:
  default:
    basic:
      contact-points:
        - ${CASSANDRA_POINT}
      load-balancing-policy:
        local-datacenter: datacenter1

kafka:
  bootstrap:
    servers:
      - ${KAFKA_SERVER}
